### ISSUE TITLE
Can't send amounts of FIL that are >n but <n+0.1 where n is an integer.

### ISSUE THREAD

**Issue by dannyob** [glifio/wallet#1010]
**Describe the bug**
Glif Wallet doesn't let you type FIL amounts larger than 1, with a zero in the first digit after a decimal point, and any other number in the second digit.

**To Reproduce**
1. Go to: wallet.glif.io and log on
2. Click on 'Send'
3. Type in a recipient address
4. Start typing "1.001"
5. After typing "1.0", the entry field will normalize "1.0" to "1".
6. Try typing another "0". The entry field will normalize it again, making it impossible to enter "1.01" or similar numbers.

**Expected behavior**
You should be able to type "1.01" straight into the entry box.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux 
 - Browser: Brave
 - Version: 1.37.109

**Comment by Schwartz10** [comment]
Hey @dannyob thanks for reporting this! This is fixed in our upcoming wallet release!

**Comment by dannyob** [comment]
Great! thanks!
