### ISSUE TITLE
Show precise balances

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#103]
Right now everyhting is rounded down, how can a user see their _exact_ filecoin balance?

**Comment by as-dr** [comment]
![image](https://user-images.githubusercontent.com/6787950/78393122-a83d1480-75bf-11ea-8c82-3a20cbe66c0b.png)

This is the furthest I had gotten it.

The idea was to also include a variable fontSize that changes based on the size of the balance (smaller font size if we need to display larger balances)

And as you can see in the screenshot, decimal amounts are separated on their own line.
