### ISSUE TITLE
glif.link - safe URL?

### ISSUE THREAD

**Issue by kleopartas** [glifio/wallet#1086]
Hello.

On this url - https://explorer.glif.io/actor/ - Wallet - wallet.glif.link 

Its safe URL?

I used my seed phrase on this URL. Please tell me I won't be hacked =)

**Comment by Schwartz10** [comment]
Yes that link is owned by the same team that runs glif.io - for now you should be good to use `glif.io` domains everywhere - like wallet.glif.io
