### ISSUE TITLE
Page should not scroll when content does not fill one page

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#109]
Right now for some reason, each nextjs page scrolls when there isn't enough content to warrant scrolling. This normally wouldn't matter, but it has bad side effects for the FloatingContainer on the send screen. 

"Hidden" floating buttons (bc it's 8px off "bottom", which you need to scroll to see):

![image](https://user-images.githubusercontent.com/12353734/75457694-c5d8e780-594a-11ea-9a6a-50bd6651de96.png)

**Comment by as-dr** [comment]
Can you also give me some insight into your setup for this issue, too? (computer, display resolution, browser looks like Chrome?) because I cannot reproduce it on the current `next` branch.

**Comment by Schwartz10** [comment]
Interesting

Chrome - Version 80.0.3987.122 (Official Build) (64-bit)
Computer - MacBook pro 2018 15 inch macOS Catalina V 10.15.2

I'm not zoomed in/out (at 100% zoom)

**Comment by Schwartz10** [comment]
Weird - closed chhrome and reopened, restarted next and this isn't happening any more. Will close for now, but lets keep a lookout for it
