### ISSUE TITLE
Fix layout of MessageHistoryRow

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#110]
![image](https://user-images.githubusercontent.com/12353734/75457805-ed2fb480-594a-11ea-9fdb-a550fb63176f.png)

**Comment by as-dr** [comment]
@Schwartz10 I'm on `next` and its rendering fine for me, apart from being very long, which will be fixed up in the layout update:

![image](https://user-images.githubusercontent.com/6787950/75467106-f4b28600-5969-11ea-8f01-ef3b70f00214.png)

Can you give me any insight into what setup you've got, so I can try and reproduce please? :)

**Comment by Schwartz10** [comment]
Restarted chrome and deleted the .next directory and this went away - same thing as https://github.com/openworklabs/filecoin-web-wallet/issues/109

closing for now but lets keep our eyes on this
