### ISSUE TITLE
Add receive screen

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#123]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/12353734/75503465-b3d76300-59a3-11ea-99a9-7f199d2e5e63.png">

**Comment by Schwartz10** [comment]
@listenaddress there are some really easy QR code libs, but idk what security implications they have. Could look to otehr OS wallets to see if/what deps they use. Or check with//use richard patel's nimiq stuff

**Comment by listenaddress** [comment]
One thing here. We'll want this receive flow to include verifying the address on the device, like LL does: https://www.are.na/block/6303603. I don't think we'll need to double check that their device is connected, but we'll want to have them verify the address on the device.

**Comment by listenaddress** [comment]
I don't think we need to check that their device is still connected but we'll want to let them verify the address on the device.

**Comment by Schwartz10** [comment]
We should pop in some ledger error handling then too

**Comment by Schwartz10** [comment]
@listenaddress https://github.com/openworklabs/filecoin-web-wallet/commit/b1e9a9c7abed482afedd7a249f93ce49233a6ee6 is a commit that adds a brand new page with some wallet validation (for account selection) - you can set yourself up here in the same exact way to make a `/receive` screen. 

The basic class is the same - check to make sure wallet exists before moving forward

**Comment by listenaddress** [comment]
Sg. Will implement when Alex is done with the design.

**Comment by as-dr** [comment]
@listenaddress I wanted to clarify here cos there has been some back and forth on the design due to us weighing up security implications of any implementation in our Slack.

What information are we going to display here, beyond their address?

Are we going to display a QR code?

Anything else?
