### ISSUE TITLE
Add tx detail screen

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#125]
@as-dr can you paste a screenshot of the design here?

**Comment by as-dr** [comment]
![image](https://user-images.githubusercontent.com/6787950/75511335-b7331480-59cc-11ea-93ec-08278c0bbd7c.png)

**Comment by as-dr** [comment]
![image](https://user-images.githubusercontent.com/6787950/75511513-31639900-59cd-11ea-99d0-7998d09c2f3b.png)
