### ISSUE TITLE
Account selection

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#133]
@as-dr going to paste screenshot

We still need a way to figure out what network is selected

**Comment by as-dr** [comment]
![image](https://user-images.githubusercontent.com/6787950/75568196-994bcb00-5a31-11ea-8cfc-6a23dc052757.png)

**Comment by Schwartz10** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/12353734/75610091-395e2e80-5adc-11ea-9211-2057e4e3fd76.png">
