### ISSUE TITLE
Center floating container in the account switcher

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#137]
- This ticket could include some other small spacing adjustments

![image](https://user-images.githubusercontent.com/12353734/75618031-f335b900-5b35-11ea-99b2-a5cafb6013a8.png)

**Comment by as-dr** [comment]
@Schwartz10 
The key here is to use the layout components that are in use for `Wallet` - `Wrapper`, `Sidebar` `Gutter` and `Content`. 

I could create a `Layouts/` folder that exports these components and then re-import them back into the `Wallet/index.jsx` file and into the `AccountSelector/index.jsx` file, too. 

Alternatively, we could import the `Wallet` and the `AccountSelector` and any other necessary screens *into* the `Layout` file... Not sure what is best practice here.

**Comment by Schwartz10** [comment]
> I could create a Layouts/ folder that exports these components and then re-import them back into the Wallet/index.jsx file and into the AccountSelector/index.jsx file, too.

^^ This

**Comment by Schwartz10** [comment]
Relates to (and will hopefully get fixed by) https://github.com/openworklabs/filecoin-web-wallet/issues/183
