### ISSUE TITLE
add gas customization

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#141]
@as-dr can you link a pic of the final (or close to final) designs here when ready?

**Comment by as-dr** [comment]
## Original
This was the one I was leaning towards, as its the simplest to implement (no sliders) and the least bs - really only for technical users who know what it does and how to operate it.

![image](https://user-images.githubusercontent.com/6787950/75674900-d350e300-5c64-11ea-8bb9-d3e239c743ae.png)

## "Full-Screen" Alternative
Alternatively, we could just overlay a new element on top of the `SendCard` so we don't have to worry about space constraints:

![image](https://user-images.githubusercontent.com/6787950/75676120-5e32dd00-5c67-11ea-8aa0-ff226ca05f51.png)

## "Full-Screen" w/ Custom Selected

![image](https://user-images.githubusercontent.com/6787950/75676162-799de800-5c67-11ea-8306-25d7ecf5a3c6.png)


## Behaviors
1. The pre-set (Slow, Medium, Fast) buttons would dynamically change the `gas amount` & `gas limit` as you clicked on them.
1. Or those inputs could be manipulated directly with custom amounts by the user.
1. The "Medium" button / flag is set by default for all FIL tx's in our wallet.
1. When the "Custom" button/flag is active, helper text is displayed "Please enter your custom amount" (or something similar)
1. The buttons inside the `FloatingContainer` are context-specific, and so on this screen they would change from progressing the send flow to allowing the user to save their custom gas selection, or cancel out of the screen entirely. This is obviously cleaner, but I can't make any guarantees that a context-specific set of buttons won't confuse some users.

**Comment by Schwartz10** [comment]
I like the full screen alternative a lot. Way more space to educate if we need in the future too.

One thing we could also add that metamask does is the fiat equivalent of the fees. What do you think about that?

**Comment by as-dr** [comment]
Yes, education will be important. E.g. Explaining what ATTAFIL (am I even spelling that right?) is vs. FIL.

As a general rule, we should always correlate FIL to a fiat rate. Good call.

![image](https://user-images.githubusercontent.com/6787950/75678076-8d4b4d80-5c6b-11ea-98ad-a89c0725cf7e.png)
