### ISSUE TITLE
UI design and implementation for "unsupported browser" page

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#180]
Hey @as-dr - there's a ["bad browser" page](https://github.com/openworklabs/filecoin-web-wallet/blob/next/pages/bad-browser.jsx) that the user gets sent to if they select ledger wallet while on any browser that's not Google Chrome.

I didn't see any figma design for this, will you paste a screen shot in here?

Thought it would be safe to implement a similar "card" ui that the rest of the onboarding has, but i held off for now.

**Comment by as-dr** [comment]
Thanks.. Will work on this on Monday.
