### ISSUE TITLE
DisconnectedDeviceDuringOperation

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#19]
1. Plug in ledger device, unlock it, open it to dashboard
2. Attempt to call `GetVersion`, call should fail ("App doesn't seem to be open")
3. Do not refresh page
4. Open Filecoin app on ledger
5. Click try again
6. DisconnectedDeviceDuringOperation: The device was disconnected.

**Comment by samsong** [comment]
Hi Same issue happens for me using Polkadot, ledger nano S, linux kubuntu (virtualbox), polkadot web app on chrome browser.
when try to create a new account with polkadot app open i get error in browser on polkadot website:

DisconnectedDeviceDuringOperation: failed to write the report
