### ISSUE TITLE
Stepper needs minwidth?

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#211]
On small view ports

![image](https://user-images.githubusercontent.com/12353734/76535178-d6ac5180-6450-11ea-8db9-8ff2cf9062f2.png)

Whats the simplest solution here?

**Comment by as-dr** [comment]
Yeah I picked up on that. It's less about the Stepper and more about the entire Card, which is collapsing to be way too small. It should have an explicit width and then `flex-wrap` at that viewport.

I will resolve this as part of our larger onboarding update.
