### ISSUE TITLE
Confirmation card bold text should be same size as the surrounding text

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#213]
![image](https://user-images.githubusercontent.com/12353734/76544523-90f68580-645e-11ea-9999-ca889e356898.png)

**Comment by as-dr** [comment]
![image](https://user-images.githubusercontent.com/6787950/76776077-0dea6d80-6785-11ea-9354-3052374c4a73.png)

Resolved in https://github.com/openworklabs/filecoin-web-wallet/pull/221/
