### ISSUE TITLE
Seed Phrase onboarding hangs first time on Loading screen.

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#256]
# Current Behavior
If you click on the "Create Wallet" (via seed phrase/mnemonic) onboarding, the `Loading` screen appears in perpetuity. User must refresh page, and click on the button again to proceed through to the correct screen.

# Expected Behavior
When user clicks on "Create Wallet" onboarding button, user is taken to that flow without the Loading screen "hanging" in perpetuity.

# Steps to reproduce
1. Load up the app
1. Click on "Seed Phrase" onboarding button
1. Observe Loading page hanging. 

**NB** I have attempted to follow these steps to reproduce the bug after seeing it this morning, but cannot. Have tried on multiple browsers and after restarting the server.

**Comment by Schwartz10** [comment]
I think this is closed after we adjusted security settings? Let's reopen if you can replicate @as-dr
