### ISSUE TITLE
Error glitch in Ledger setup

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#272]
# Expected Behavior
Correct error styling appears alongside explicit copywriting guiding the user to the actions necessary to resolve the error.

# Current Behavior
![image](https://user-images.githubusercontent.com/6787950/78035950-1bd0ee80-7340-11ea-80cc-f221dfa4291c.png)

# Steps to reproduce
1. Have a pending tx up on the ledger.
1. Click on 'Ledger onboarding'
1. Reject tx on the Ledger
1. Click 'Next' to proceed to Step 2 in Ledger onboarding
1. Error card comes up ("Had difficulty connecting to your Ledger. Please plug & unplug")
1. Do not plug & unplug Ledger.
1. Click 'Back' to return to Home setup page.
1. Click 'Ledger' onboarding again
1. Observe mistyled error state with vague copywriting.

**Comment by Schwartz10** [comment]
@as-dr this is fixed in my open branch with wallet provider testing :D

**Comment by as-dr** [comment]
You son of a 😏 👏
