### ISSUE TITLE
Improve distinction between sent / received transactions and their status

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#279]
@as-dr can we paste a design in here?

**Comment by as-dr** [comment]
With account avatars
![image](https://user-images.githubusercontent.com/6787950/78280375-5af17200-74ef-11ea-9ba8-93ca9ac53c78.png)



Without account avatars
![image](https://user-images.githubusercontent.com/6787950/78280335-4c0abf80-74ef-11ea-9814-2c82710a9346.png)

**Comment by Schwartz10** [comment]
@as-dr can you take the implementation on this one?

**Comment by as-dr** [comment]
@Schwartz10 Yeah I'm planning on tackling this next.
