### ISSUE TITLE
Update button copy, state during send flow

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#296]
Per Eva's feedback:

1. - [x] Don't disable `Next` button inside of Send flow.
1. - [x] Set `Send` & `Receive` buttons in `BalanceCard` to `opacity: 0.5;` and disable while Send flow is active.
1. - [x] Rename `Next` button to `Send` button.

**Comment by Schwartz10** [comment]
Hey @as-dr - if there's an invalid form when a user tries to submit, do we want to use the error Card to explain the error? Or just display the errors inside the SendCard itself and only show non-user errors in the error card?

**Comment by as-dr** [comment]
@Schwartz10 Yeah I think only for non-user errors. This way, we can position errors close to where the error occurred (address errors below the recipient input, funds errors next to the funds input, etc.)
