### ISSUE TITLE
Update"GasCustomization" component, update its integration into SendCard

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#297]
Per Eva's feedback:

# To Do 
1. - [ ] Update `GasCustomization` integration into SendCard so it is displayed alongside the other content, instead of obscuring it.
1. - [ ] Rename "Gas Price" and "Gas Limit" to "Transaction Price" and "Transaction Limit"
1. - [ ] Add tooltips to the above explaining what "Price" and "Limit" refer to.

**Comment by Schwartz10** [comment]
Reminder for me to add the estimated gas to the transaction total on the send card. That can go in this PR.
