### ISSUE TITLE
Fix display of large numbers in TransactionDetails & SendCard components

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#314]
Example:

![image](https://user-images.githubusercontent.com/6787950/78400706-9b272200-75cd-11ea-9f96-355a531242cc.png)

**Comment by as-dr** [comment]
@Schwartz10 Arguably we could follow the same protocol per what we're doing to the FIL balance inside the MessageHistoryRow component - If it's smaller than N, display it as `<0.000001FIL`

**Comment by Schwartz10** [comment]
Yup, also i'll add the pretty / precise clickers too. Gonna take this
