### ISSUE TITLE
Assess the feasibility of conditionally styling amount inputs based on length

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#326]
We had discussed the idea of conditionally reducing the font-size of the BalanceCard FIL number string if it goes beyond N numbers (e.g. If the balance is > 9 numbers, reduce font-size to the next value in the font-sizes array in the theme file.

But we need to assess the viability / ROI of this and will come back to it later.

![image](https://user-images.githubusercontent.com/6787950/78572941-7bc30b80-77fe-11ea-9fbe-d248778d9b15.png)

**Comment by as-dr** [comment]
FWIW this sounds like very, very low priority polish stuff. Think we can put it at the bottom of the pile for now. And I'm sure there are simpler solutions/alternatives we could implement..

**Comment by Schwartz10** [comment]
@as-dr is this still relevant?

**Comment by as-dr** [comment]
@Schwartz10 No, I don't think this is necessary with the exact/approx approach we have now.
