### ISSUE TITLE
AccountSelector page still accessible if Ledger has timed out

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#336]
# Current Behavior
User's can still navigate to the account selector page (via "Switch" button) and click "Create account" despite the fact that the Ledger is logged out.

Instead of showing an error, the Create Account button displays the "Loading" indicator (which makes it appear as though it is in the process of creating an account) but then exits the loading state and nothing else happens.

# Expected Behavior
If a user is accessing Glif via Ledger and it times out, any action should show either return them to the onboarding or - ideally - display a global error within a fixed position modal that asks them to activate / unlock their Ledger again.

# Steps to Reproduce
1. Go through Ledger onboarding
1. Wait for Ledger to time out
1. Click 'Switch'
1. Click 'Create Account button.

**Comment by Schwartz10** [comment]
@as-dr what do you mean by:

> Wait for Ledger to time out

How do you make that happen? Unplug it?

**Comment by as-dr** [comment]
That or just wait 5 minutes or so.

**Comment by Schwartz10** [comment]
Ahhhh right, i forgot i put my device settings on never auto-lock lol. thx
