### ISSUE TITLE
"copy" label in account card should be clickable along with the icon

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#341]
When you hover over the click icon, the "copy" text appears, but it doesn't do anything when you click it. Could cause confusion. 

One thing we can do is wrap the icon and the Copy text in its own div, and lift the `onClick` handler up one level higher so clicking the `div` copies the text instead of the icon

**Comment by as-dr** [comment]
I mean we should just make the whole thing a `Button` component, then, no?

**Comment by Schwartz10** [comment]
Yeah that sounds good. I'm gonna assign this one to @listenaddress. If you pass `role="button" type="button"` as props to the wrapper div, it will _look_ like a button on the dom i think, without hhaving to worry about all the styling crap that comes with using a native html button (or one of our own, homemade buttons)
