### ISSUE TITLE
fix back button behavior on onboarding

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#356]

**Comment by Schwartz10** [comment]
@as-dr i can't seem to replicate this on my chrome. Can you try restarting everything, quitting chrome, not making any code changes, and doing this again? Wondering if this had something to do with a weird state being stuck in HMR 

if you can replicate, what borwser / version are you on?

**Comment by as-dr** [comment]
Very weird,  I can't get it to replicate anymore.
