### ISSUE TITLE
RPC ERROR

### ISSUE THREAD

**Issue by lishuailibertine** [glifio/wallet#362]
error message

send request:   MpoolPush

{
    error =     {
        code = 1;
        message = "missing permission to invoke 'MpoolPush' (need 'write')";
    };
    id = 1;
    jsonrpc = "2.0";
}

**Comment by Schwartz10** [comment]
@lishuailibertine need some more info from you on this. Can you describe how to replicate? Where is this code running? What node are you pointing to?

**Comment by lishuailibertine** [comment]
web demo node url:  https://proxy.openworklabs.com/rpc/v0

Where is the browser address of this node？

**Comment by Schwartz10** [comment]
> web demo node url: https://proxy.openworklabs.com/rpc/v0 

This is not intended as a web demo URL. This is the lotus node we use to interact with the Filecoin network. 

I'm closing this issue for lack of a clear description of a bug or feature request. If you are able to give a clear representation of something not working, please file a new issue.
