### ISSUE TITLE
Short addresses don't get truncated properly

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#371]
For example, `t0123` is truncated to `t0123 ... 0123`.

**Comment by Schwartz10** [comment]
How do you derive a short address? Where would those come from?

**Comment by listenaddress** [comment]
https://github.com/filecoin-project/go-address/blob/eb9bb40ed5be1647421996537f4da190463a921f/address_test.go#L40

**Comment by listenaddress** [comment]
Those are some test cases that show different addresses including some short ID protocol addresses. The payload of ID protocol addresses are leb128-varints, so they can be really small.

**Comment by Schwartz10** [comment]
Do you want to fix this then @listenaddress? Just don't truncate addresses less than a certain length?

**Comment by listenaddress** [comment]
Yerr!
