### ISSUE TITLE
Unsupported Device screen triggers on large displays

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#388]
# Current Behavior
When using Chrome's device testing for 4k displays (2560x) the Unsupported Device error page renders

# Expected Behavior
Large scale displays should be accounted for.

# Steps to Reproduce
1. Open up site in Chrome
1. Open up Chrome Inspector ( `SHIFT` + `CMD` + `i`)
1. Open up Device Toolbar (`SHIFT` + `CMD` + `M`)
1. Click 'Responsive' if not already toggled
1. Click on the second outer most "bar" or hardcode a width in the width input (see screenshot for ref)

<img width="893" alt="Screen Shot 2020-04-15 at 11 36 17 AM" src="https://user-images.githubusercontent.com/6787950/79350185-815ed680-7f0d-11ea-84df-cb4c5901cc63.png">

#Reference
![image](https://user-images.githubusercontent.com/6787950/79348695-b702c000-7f0b-11ea-8c6f-2e763c44ccd3.png)

**Comment by listenaddress** [comment]
I'll grab this. Need a test for this too.

**Comment by listenaddress** [comment]
Actually I think this is right. When you use responsive mode they mock a mobile user agent in `window.navigator.userAgent`. It's something like `Mozilla/5.0... Mobile ...`. That's a mobile user agent so we want to display this screen, no?

**Comment by as-dr** [comment]
We got someone with a giant screen we can test this on? :P

**Comment by listenaddress** [comment]
I'm not sure the screen would matter. I think once you enter responsive mode, it sets the user agent as a mobile user agent?
