### ISSUE TITLE
How do I know how to generate an address？

### ISSUE THREAD

**Issue by Wangmmx** [glifio/wallet#435]
Hello, I would like to ask about the implementation method of specific address generation.I ran the program and chose to import the private key on the page. I imported the secp256k1 type of private key generated before, and then the address appeared on the page. I want to know how the private key to the address is calculated. Could you please tell me Step?

**Comment by Schwartz10** [comment]
Hey! We use the zondax signing library tools for all cryptographic operations. https://www.npmjs.com/package/@zondax/filecoin-signing-tools - their github is probably the best place to find that information.
