### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mistricky** [glifio/wallet#483]
Hi! I'm so glad to see this filecoin wallet, but when I try to start this project by `yarn dev`, I get the following error
```
POST https://node.glif.io/02/rpc/v0 503 (Service Temporarily Unavailable)
```
and the wallet was disconnected that I can't continue

can u help me?

**Comment by Schwartz10** [comment]
Hi @youncccat - the Filecoin network has been a bit shaky these past few days, the nodes that back this wallet are up/down frequently. 

You can always spin up a local devnet using the instructions here https://docs.lotu.sh/en+setup-local-dev-net and then adjust your next config to hit your local node https://github.com/openworklabs/filecoin-web-wallet/blob/primary/next.config.js#L20
