### ISSUE TITLE
Spacing in the multisig card looks a little off/weird

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#484]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/12353734/91897137-d6567b80-ec67-11ea-9bea-b1d3d0a13833.png">

Chrome

**Comment by as-dr** [comment]
Not sure what happened here. Looks like some of my code wasn't committed or was overwritten.. Maybe something to do with the updates to the core wallet that have found their way here.

Nevermind, it'll be easy to fix.
