### ISSUE TITLE
Available/vesting balance could be distinguished more

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#485]
I see the `Available` Tab Hovers when its clicked, but i think the color should change too 

When I'm on TotalVesting, it still looks (to me) like i'm on available
<img width="500" alt="image" src="https://user-images.githubusercontent.com/12353734/91897204-eff7c300-ec67-11ea-9b24-f7f02233d10f.png">

**Comment by Schwartz10** [comment]
Ah i forgot this was a percentage thing... i wonder if theres a diff graphic we could use? I'm not sure that information will be received and interpreted as it is intended 

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/12353734/91897639-95ab3200-ec68-11ea-9bb6-c9aebd4cc754.png">

**Comment by as-dr** [comment]
Yeah, I said when I came up with that concept that it's probably "too clever by half" and would either be missed, or just create confusion. 

We'd probably have to add some copy to communicate what that means. The visual element alone isn't enough. Let me think on it.

**Comment by Schwartz10** [comment]
@as-dr one idea is to show the "locked" amount next to the "available" amount. This will actually be easier in code too.

**Comment by as-dr** [comment]
**NB** This will be resolved with the updated msig v2 design
