### ISSUE TITLE
How do I build my own server API

### ISSUE THREAD

**Issue by LTAND** [glifio/wallet#492]
![image](https://user-images.githubusercontent.com/29198894/92090582-2bc69000-ee02-11ea-94f8-bd808b5c380e.png)

**Comment by Schwartz10** [comment]
The filscan and filscout APIs are used to construct the message history table. If you want to build your own server to populate this table, you should rewrite the `useMessageHistory` hook https://github.com/openworklabs/filecoin-web-wallet/blob/primary/components/Wallet/Message/useTransactionHistory.js and format the message accordingly https://github.com/openworklabs/filecoin-web-wallet/blob/primary/components/Wallet/Message/formatMessages.js
