### ISSUE TITLE
Add copy button to ledger address

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#496]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12353734/92187943-2e88ab80-ee29-11ea-9de6-5febc9b82eb6.png">

**Comment by Schwartz10** [comment]
Also the "view" button might not be obvious that means "on the device"

**Comment by as-dr** [comment]
I've got some design ideas for this, gonna tackle them this week.
