### ISSUE TITLE
non-standard bip44 derivation path

### ISSUE THREAD

**Issue by kumavis** [glifio/wallet#498]
The current glif wallet HD derivation path is
```
m / purpose' / coin_type' / account / change / address_index
```
https://github.com/openworklabs/filecoin-web-wallet/blob/a297b5ac83825ea96ffff6654c986fc1b96e06b5/utils/createPath/index.js#L6

this differs from the [bip44 standard](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#path-levels)
which is 
```
m / purpose' / coin_type' / account' / change / address_index
```
( notice the `account` section is "hardened" by appending the apostrophe )

:warning:  note that fixing this to comply with the standard will cause your wallet to generate different keys than before

**Comment by danfinlay** [comment]
This is a really easy mistake to make, we've absolutely dealt with similar BIP44 compatibility issues at MetaMask, and it's really great to nip these in the bud early (like during testnet days!) to ensure future compatibility with the broadest set of other wallets, especially ones that try to accommodate multiple chains.

**Comment by kumavis** [comment]
maybe relevant https://github.com/Zondax/filecoin-signing-tools/issues/274

**Comment by Schwartz10** [comment]
Thank you both so much for catching this! I was clearly confused... 

If you see any other areas inside the wallet that will improve our chances of interoperability with other networks, chains, MetaMask...etc please let me know. (Also feel free to leave _any_ suggestions you have about wallet architecture, ways to improve in general...etc!)
