### ISSUE TITLE
Send Flow: Custom gas send flow 

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#542]
Juan's feedback:

[Consider adding slow/med/fast custom gas](https://www.figma.com/file/yFieZsi9BAY7gyfUQPwFro?node-id=1457:6541#40870620)

**Comment by Schwartz10** [comment]
I checked in with Kubuxu on https://github.com/filecoin-project/lotus/issues/3326 and this is still a premainnet issue that will get resolved. Once that's merged, this can go
