### ISSUE TITLE
Seed phrase isn't valid and not sure why

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#561]
Pasted seed phrase with format:
```
word1 word2...
```

and I get this.
<img width="642" alt="Screen Shot 2020-09-22 at 2 31 27 PM" src="https://user-images.githubusercontent.com/8434548/93922779-683e2b00-fce0-11ea-8aaf-20199eb2166f.png">

Not clear what's wrong with it. Is it too long? Is there a word that isn't valid?

**Comment by Schwartz10** [comment]
Hey @listenaddress this comes directly from bip39 lib https://github.com/openworklabs/filecoin-web-wallet/blob/37c5e0d24275b651c29106be22f289b74d11c7d2/components/Onboarding/Configure/ImportMnemonic/index.jsx#L39

**Comment by listenaddress** [comment]
Wowww I wrote down trail instead of trial. 

Would be really nice to have a tool that says "are you sure you didn't mean trial?"
