### ISSUE TITLE
Error setting up SAFT after using wallet

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#563]
On Windows I was using the wallet then opened up the SAFT flow. I'm _pretty sure_ I had just entered my investor ID when I got this. If it wasn't that step it was the first in the flow. Right around there. Gonna test again.

![Screenshot (1)](https://user-images.githubusercontent.com/8434548/93942557-a64a4780-fcfe-11ea-9fd2-f78955f214a9.png)

**Comment by Schwartz10** [comment]
will get fixed with https://github.com/openworklabs/filecoin-web-wallet/issues/571
