### ISSUE TITLE
Add a screen that explains what to look for on the Ledger when signing a msig tx

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#567]

**Comment by as-dr** [comment]
Feels like this could be a good candidate for a modal, so we don't break the user's understanding of "where" they are. 

Keeping them in the msig screen and displaying a modal would maintain spatial causation -- communicating that they are still in the "msig space" and that the information is related to their transaction, and is a necessary part for them to complete the tx (unless I misunderstand what is being proposed here)
