### ISSUE TITLE
Wallet is taking me back home randomly

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#592]
I'm getting taken back home at random times. Not seeing anything obvious in the console. 

<img width="1092" alt="Screen Shot 2020-09-23 at 10 00 42 PM" src="https://user-images.githubusercontent.com/8434548/94092288-5a73cd00-fde8-11ea-9acf-8122aa504538.png">

**Comment by listenaddress** [comment]
Got this with Ledger and imported seed.

**Comment by Schwartz10** [comment]
HMR most likely if you're running locally. See if you can repro on prod
