### ISSUE TITLE
Provide more details, solution in "[address] has sufficient funds" Error Card variant

### ISSUE THREAD

**Issue by as-dr** [glifio/wallet#627]
# Reference
![image](https://user-images.githubusercontent.com/6787950/94599040-3c81ee80-0266-11eb-953e-8159bff58166.png)

This card should have additional information. Specifically:

1. Where is this account? (on the Ledger device)
1. What does the user need to do to rectify this situation (increase the amount of FIL on the linked Ledger account attached to their msig)

**Comment by Schwartz10** [comment]
@as-dr https://github.com/openworklabs/filecoin-web-wallet/blob/primary/components/Msig/Withdraw/index.jsx#L141 is where you want to look at for that error message btw
