### ISSUE TITLE
Style bug: buttons fixed at the bottom of screen

### ISSUE THREAD

**Issue by jbenet** [glifio/wallet#649]
buttons appear fixed to the bottom of the screen (chrome)

![image](https://user-images.githubusercontent.com/138401/95676549-a6a66780-0b73-11eb-9484-b41aed40c2c0.png)

**Comment by as-dr** [comment]
@jbenet Thanks for submitting this. We can establish a `maxHeight` to limit the `flexGrow` property from pushing the buttons down to the bottom of large screens.

Out of curiosity, what's the resolution/dimensions of your monitor?
