### ISSUE TITLE
Need docs for "what should I see on my Ledger" in vault withdrawal process

### ISSUE THREAD

**Issue by autonome** [glifio/wallet#739]
Screenshot of link in Glif vault UI:

<img width="767" alt="Screen Shot 2020-12-06 at 9 40 17 AM" src="https://user-images.githubusercontent.com/50103/101283345-b7581000-37a7-11eb-8db9-38f1f1480d3d.png">

Links to:

https://reading.supply/@glif/what-to-look-for-on-your-ledger-device-when-submitting-a-multi-sig-transaction-gQXIX6

Which says "coming soon".

**Comment by listenaddress** [comment]
Ahh shoot, good catch. Thanks Dietrich! We need to add this doc (https://paper.dropbox.com/doc/Using-Glif-Vault-Multisig--BAz5R6WG2clrUQgpyTnM0eHhAg-H297jDNq53qQwcjSvWkcU) to Reading Supply. Will do v soon.
