### ISSUE TITLE
Glif Doesn't Recognize Ledger Wallet

### ISSUE THREAD

**Issue by Surfmonkey65** [glifio/wallet#749]
The Glif wallet doesn't recognize the ledger device and continuously reads "please connect the ledger device."

Pressing "yes my ledger is connected" doesn't change anything. 

I am running the Brave browser and disabled Malware and Norton to test if that changed the outcome - no dice. 

Recommended work around? 

![image](https://user-images.githubusercontent.com/31426727/103026484-49367b80-4511-11eb-8840-2ed35685b862.png)

**Comment by zebul** [comment]
I am having the same issue.  Were you able to solve this?

**Comment by zebul** [comment]
This issue appears to only be happening on Windows/Chrome.  I was able to use the wallet with my ledger device on Ubuntu/Chrome

![image](https://user-images.githubusercontent.com/1380654/103725084-a9560480-4f8a-11eb-8464-8f4a4675e003.png)
![image](https://user-images.githubusercontent.com/1380654/103725100-b5da5d00-4f8a-11eb-92dc-10bb34cd5383.png)

**Comment by Surfmonkey65** [comment]
Thanks @zebul. Trying on my ubuntu and receive the secure connection error "err_ssl_version_or_cipher_mismatch"

Is this an issue for anyone else?

I may just need to bypass it but not quite sure how.

**Comment by zebul** [comment]
@Surfmonkey65 are you using Brave or Chrome with Ubuntu? I got an error on Glif saying that it only worked with Chrome when I tried to use firefox.  

I did initially have an issue connecting the ledger via Ubuntu but was able to solve that by installing the Ledger Live application on Ubuntu and running  the command "wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash" which I found here https://support.ledger.com/hc/en-us/articles/360006395553-Download-and-install-Ledger-Live

**Comment by Schwartz10** [comment]
Hey @zebul and @Surfmonkey65! I'm so sorry for the delay in getting back to you!

Chrome 87 released a new USB backend that broke things. You can go to [chrome://flags#new-usb-backend](chrome://flags#new-usb-backend) and disable it. This should get you going again. 

I'm closing this issue in favor of: https://github.com/glifio/wallet/issues/759, but feel free to reopen or keep commenting if this does not fix the issue for you.

**Comment by aschmahmann** [comment]
@Schwartz10  I'm still experiencing issues on Windows even with new-usb-backend disabled.

I make it past the first screen, but then things either:
1) Die on the second screen with `Oops! Please quit the Filecoin app, and unplug/replug your Ledger device, and try again.`
2) Make it through and show my balance, but hang/die if I try to interact with the ledger (e.g. show my address, or switch addresses)
   - If I unplug/replug the Ledger then I can get it to show my address once, but I can't get it to do it a second time without unplug/replug again

Note: my Ledger also occasionally freezes up during this process.

**Comment by Schwartz10** [comment]
Hmmm this sounds like it might be a different issue. Folks who disabled the USB backend fixed the issue where their Ledger wasn't even a visible option to connect to.

Would you mind opening up a new ticket for this? Please include:

- Windows version
- Chrome version
- Ledger firmware version
- Filecoin app version
- As clear steps to replicate / any applicable screenshots
