### ISSUE TITLE
"Ledger device locked or busy" error when Ledger isn't locked or busy

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#77]
We may want to follow this error up with something like "If it's not busy, try unplugging and re-plugging your Ledger in".

**Comment by Schwartz10** [comment]
Do you remember how you made this happen?

**Comment by Schwartz10** [comment]
@listenaddress can you repro?

**Comment by listenaddress** [comment]
I reproduced a couple times, forget the exact flow. Will try to note next time.

**Comment by Schwartz10** [comment]
@listenaddress going to close this, but reopen if you can replicate.
