### ISSUE TITLE
Windows + Ledger troubles

### ISSUE THREAD

**Issue by aschmahmann** [glifio/wallet#779]
@Schwartz10 following up from https://github.com/glifio/wallet/issues/749#issuecomment-810396255. I can try and post screenshots when I get a chance, but lmk if there's anything you want in particular or any other way I can help with debugging.

- Windows version: Window 10 Pro - Version 10.0.19042 Build 19042
- Chrome version: Version 89.0.4389.114 (Official Build) (64-bit)
- Ledger firmware version: 1.2.4-5 (Nano X)
- Filecoin app version: v0.18.2

- As clear steps to replicate / any applicable screenshots
   1. Plug in Ledger (leave locked)
   2. Click `Login via Ledger Device`
   3. Unlock Ledger and click `Yes, my Ledger device is connected`
      - This will fail
   4. Open Filecoin app and click `Yes, my Ledger device is connected`
   5. A single option will come up as Unknown Device instead of Nano X, click it
   6. Click `My Ledger device is unlocked & Filecoin app open`
      - Sometimes Ledger device hangs and you get `Oops! Please quit the Filecoin app, and unplug/replug your Ledger device, and try again.`
      - Make it through and show my balance, but hang/die if I try to interact with the ledger (e.g. show my address, or switch addresses)
        - If I unplug/replug the Ledger then I can get it to show my address once, but I can't get it to do it a second time without unplug/replug again

**Comment by Schwartz10** [comment]
Thank you for the detailed info @aschmahmann! Haven't come across this one yet, and sorry you're experiencing trouble with the wallet! 

In step iii. - Unlock Ledger and click Yes, my Ledger device is connected (which fails).

Could you elaborate on the failure here? Also, could you open the chrome console (https://balsamiq.com/support/faqs/browserconsole/#google-chrome) and tell me what errors you see in there?

**Comment by aschmahmann** [comment]
> Could you elaborate on the failure here?

No compatible devices found in the popup, followed by the console error:

```
 ...args Unhandled error in setLedgerProvider: No device selected. Error
    at new t (https://wallet.glif.io/_next/static/chunks/b296e7c940ddd04940afe8e4625307e87076c511.6fd7327fac2ef7486293.js:1:50019)
    at https://wallet.glif.io/_next/static/chunks/b296e7c940ddd04940afe8e4625307e87076c511.6fd7327fac2ef7486293.js:1:58086
```

Some errors that I can see in step vi are:
```
...args Lost connection with Ledger. Please quit the Filecoin app, and unplug/replug device. Error: Lost connection with Ledger. Please quit the Filecoin app, and unplug/replug device.
    at f (https://wallet.glif.io/_next/static/chunks/781113562e1fcb43e7905e2224d379ee04b51422.91ff3bb8d342800dd5a0.js:1:20079)
    at https://wallet.glif.io/_next/static/chunks/781113562e1fcb43e7905e2224d379ee04b51422.91ff3bb8d342800dd5a0.js:1:20785
    at s (https://wallet.glif.io/_next/static/chunks/commons.bdd84f2f072ada4411f6.js:1:29838)
    at Generator._invoke (https://wallet.glif.io/_next/static/chunks/commons.bdd84f2f072ada4411f6.js:1:29591)
    at Generator.next (https://wallet.glif.io/_next/static/chunks/commons.bdd84f2f072ada4411f6.js:1:30197)
    at i (https://wallet.glif.io/_next/static/chunks/5a876497f04dd9c8b0da057ca25e3ff2757c08e1.fb0059e0a90530fc3cb0.js:1:332197)
    at s (https://wallet.glif.io/_next/static/chunks/5a876497f04dd9c8b0da057ca25e3ff2757c08e1.fb0059e0a90530fc3cb0.js:1:332400)
```

or less commonly (maybe when trying to unplug + replug during this process)

```
...args RangeError: Trying to access beyond buffer length Error: RangeError: Trying to access beyond buffer length
    at f (https://wallet.glif.io/_next/static/chunks/781113562e1fcb43e7905e2224d379ee04b51422.5844f7d3cb7df20ab316.js:1:19753)
    at https://wallet.glif.io/_next/static/chunks/781113562e1fcb43e7905e2224d379ee04b51422.5844f7d3cb7df20ab316.js:1:20355
    at l (https://wallet.glif.io/_next/static/chunks/commons.b942af764dfe86aacd31.js:1:30609)
    at Generator._invoke (https://wallet.glif.io/_next/static/chunks/commons.b942af764dfe86aacd31.js:1:30397)
    at Generator.next (https://wallet.glif.io/_next/static/chunks/commons.b942af764dfe86aacd31.js:1:31034)
    at i (https://wallet.glif.io/_next/static/chunks/5a876497f04dd9c8b0da057ca25e3ff2757c08e1.3bb94e29919fffbb93ac.js:1:1051885)
    at s (https://wallet.glif.io/_next/static/chunks/5a876497f04dd9c8b0da057ca25e3ff2757c08e1.3bb94e29919fffbb93ac.js:1:1052088)
```

**Comment by aschmahmann** [comment]
@Schwartz10 any updates here or any other info I can help you collect for debugging purposes?

**Comment by Schwartz10** [comment]
@aschmahmann I'm sorry to have left you hanging here - we've notified the Ledger team of the issue, and we're working on figuring out a fix. It seems that Chrome has suddenly stopped supporting the transport we use to communicate with Ledger devices on Windows computers.

This is an absolutely unsatisfactory answer, but Ledger + Chrome work reliably on Mac computers, so if you or a friend have one available, you should have no problems there. I will keep this issue open until it gets resolved, and feel free to ping me anytime with updates.

**Comment by aschmahmann** [comment]
No worries, sometimes these things take time and people get busy. I've got my backup machine ready for my Glif needs 😄.

Is this something where a third party change (e.g. a Chrome update, or a Ledger firmware update) is likely to resolve the problem and so I should check on it every so often and report back if the situation changes, or is it more likely to be on the Glif end and I should assume no changes until I get a notification here?

**Comment by Schwartz10** [comment]
Hey @aschmahmann - this is moreso where a third party change (Chrome or Ledger transport update) will hopefully resolve the problem. Windows machines, browsers, and Ledgers commonly run into issues, but we've let the Ledger team know. We haven't forgot about this, but it likely won't be a super quick turnaround on our end to get this fixed (unfortunately). I know how frustrating that can be, and I'm sorry about the trouble!

Thank you again for providing great detail in this issue.

**Comment by Schwartz10** [comment]
Hey @aschmahmann would you mind trying out https://glif-wallet.vercel.app/ on your windows computer to see if you can connect there?

**Comment by aschmahmann** [comment]
@Schwartz10 it appears to be working now, although I haven't exercised the full range of functionality.
