### ISSUE TITLE
problem to open ledger nano s

### ISSUE THREAD

**Issue by jamescjw** [glifio/wallet#788]
- What version of chrome you're using
   89.0.4389.114

- What firmware Ledger Nano S you're running
  1.6.1
![image](https://user-images.githubusercontent.com/50795515/113315343-c4dd6b00-933f-11eb-98fe-7263c78a1bb0.png)

- Filecoin app version
  0.18.2
![image](https://user-images.githubusercontent.com/50795515/113315428-dde61c00-933f-11eb-99a6-915553378e7f.png)

- Machine OS and version (I'm presuming this is a windows computer)
  win7 sp1
- Any/all steps to replicate your issue, screenshots are helpful too.
   when i used the chrome Incognito mode to start the Glif Vault, 
   It stops as the picture below, but my Ledger has been plugged in and started filecoin in the ledger. 
   Disabing the new USB backend will directly cause chrome to not find the ledger.
![image](https://user-images.githubusercontent.com/50795515/113315583-05d57f80-9340-11eb-90f3-374aa797aa7e.png)

**Comment by jamescjw** [comment]
any one here ? thank you!

**Comment by Schwartz10** [comment]
Hey @jamescjw - sorry it took so long for us to get back to you on this. This seems to be a very similar behaving problem to https://github.com/glifio/wallet/issues/779, so we can track the issue progress there.

**Comment by Schwartz10** [comment]
Hey @jamescjw would you mind trying https://glif-wallet.vercel.app/ to see if you can connect to your Ledger device there on windows?
