### ISSUE TITLE
Add bug reporting

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#79]

**Comment by listenaddress** [comment]
MEW has this manual/immediate issue debugging help that's pretty nice. 

<img width="382" alt="Screen Shot 2020-02-05 at 4 09 28 PM" src="https://user-images.githubusercontent.com/8434548/73894617-e91fe380-4831-11ea-8fd3-f59eb6243105.png">

And then a way to properly report bugs.

<img width="502" alt="Screen Shot 2020-02-05 at 4 10 49 PM" src="https://user-images.githubusercontent.com/8434548/73894670-18365500-4832-11ea-89b1-3829a7951b23.png">

**Comment by Schwartz10** [comment]
@listenaddress @as-dr i think this is pretty dope. Can we do something similar but easier?  Maybe just open up a new email address to ahoy@owl for them?
