### ISSUE TITLE
Investor ID

### ISSUE THREAD

**Issue by dombrown22** [glifio/wallet#811]
I am trying to self custody by FIL and there is no option to input investor ID?

**Comment by dombrown22** [comment]
https://paper.dropbox.com/doc/Self-Custodied-SAFT-Guide--A71I2OQNrMoMKsDk58k7vrviAg-dHxZu59oAeSw03RrRpCrd

**Comment by Schwartz10** [comment]
Hi @dombrown22 the link you pasted has the instructions I think you're looking for. I'm going to close this issue for now, but reopen if you have more questions.

**Comment by dombrown22** [comment]
Issue not fixed.
The instructions linked direct me to input an investor ID into glif, This options is not present in the glif wallet, only an actor ID.

**Comment by Schwartz10** [comment]
Ahhh @dombrown22 sorry I misunderstood. I'll have to speak with some folks from Protocol Labs to get a better sense of what to do. Will respond here with more information
