### ISSUE TITLE
Make "Unable to claim interface." error more clear

### ISSUE THREAD

**Issue by listenaddress** [glifio/wallet#83]
We may want to add something like "Check to see if your Ledger device is being used in another app."

**Comment by Schwartz10** [comment]
How did you make this error happen?

**Comment by Schwartz10** [comment]
@listenaddress bump

**Comment by listenaddress** [comment]
I had another app using the Ledger. When I tried to reproduce I got this though. 
<img width="316" alt="Screen Shot 2020-02-27 at 10 00 49 AM" src="https://user-images.githubusercontent.com/8434548/75472937-2b2bd900-5949-11ea-891c-8baf22f8a459.png">

**Comment by listenaddress** [comment]
Reproduced this by having the wallet open in localhost in one window, with my device connected, and then I tried to connect the wallet in another tab on wallet.openworklabs.com.

**Comment by listenaddress** [comment]
It's not an inaccurate message but adding to it would be cool. We'd essentially have to check the error string, and if it's === this error, we'd add to it, right?
