### ISSUE TITLE
Get ledger in bad state

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#86]
1. Open up wallet main screen
2. navigate to switch accounts
3. switch from testnet to mainnet accounts
4. while mainnet accounts are loading, click "show address on ledger device"
5. broken

The "show address on ledger device" option should only be available when there is a selected wallet (with a path) in redux.

**Comment by listenaddress** [comment]
Closing. Added checks. https://github.com/openworklabs/filecoin-web-wallet/commit/76a8f402acab04c01411dd36500423411d573f3f
