### ISSUE TITLE
add "try restarting browser" suggestion to documentation and to error messages

### ISSUE THREAD

**Issue by autonome** [glifio/wallet#884]
Often when I get an inexplicable error, restarting Brave fixes the problem. I've seen many other reports of similar pattern. This recommendation should be added in the UI and docs to aid users.

**Comment by Schwartz10** [comment]
Thanks @autonome! We have a new build coming with much better ledger error handling, but I want to make sure this one is handled well. Do you have steps to replicate? Is your device connected to two or more apps when Brave is opened before browser restart?

**Comment by autonome** [comment]
Hmm I don't have exact STR unfortunately. I'll keep an eye out once new version ships. Can you poke here when I should try again?

This one was reported by someone who saw this error. Restarting the browser fixed the problem.

<img width="1269" alt="Screen Shot 2021-10-04 at 9 45 54 AM" src="https://user-images.githubusercontent.com/50103/136445796-3918babb-561a-4f70-9377-d81f357c085d.png">
