### ISSUE TITLE
Balance is 0FIL

### ISSUE THREAD

**Issue by longren610** [glifio/wallet#922]
Login http://localhost:3000/ is successful but the balance is 0FIL, but the transaction record shows that it has received 0.1FIL.
Log in using https://wallet.glif.io/, the balance can be displayed normally as 0.1FIL, and the transaction records are also normal.
How do I do it?

![image](https://user-images.githubusercontent.com/26690413/145758519-59b62d9b-a548-455d-964d-109c418ea823.png)

**Comment by longren610** [comment]
In https://wallet.glif.io/
![image](https://user-images.githubusercontent.com/26690413/145758977-cef536a1-ce33-4697-abb2-41c6c267bc02.png)

**Comment by fhmd4k** [comment]
how to solve?
