### ISSUE TITLE
Transaction history is stale after switching wallet

### ISSUE THREAD

**Issue by Schwartz10** [glifio/wallet#945]
1. Load up your default wallet
2. Switch wallet
3. See transaction history from previous wallet?

Almost like the useQuery hooks dont react to the prop changes to the address variable?

**Comment by Schwartz10** [comment]
This still seems to _occasionally_ happen, but i can't tell yet how to replicate reliably.

There are also several queries that are obviously getting made, so ideally we test this where data is fetched from each query, and we see that each one returns fresh information on a per address basis

**Comment by navFooh** [comment]
Not being able to replicate this at the moment

**Comment by Schwartz10** [comment]
It's possible it was an artifact of other errors going on in the hooks that are now fixed? I'll keep it open a little longer and close it if we don't see it for a bit
